"""Add temporary dummy column

Revision ID: 82adbeed742d
Revises: 429eeb574d36
Create Date: 2025-04-06 23:29:12.859085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82adbeed742d'
down_revision = '429eeb574d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_column', sa.String(length=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dummy_column')

    # ### end Alembic commands ###
