"""Remove dummy column

Revision ID: faa542dd330a
Revises: 82adbeed742d
Create Date: 2025-04-06 23:32:11.595846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faa542dd330a'
down_revision = '82adbeed742d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('dummy_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_column', sa.VARCHAR(length=1), nullable=True))

    # ### end Alembic commands ###
